from app.config.database.init_data.categories import (
    img2img,
    inpainting,
    text2img,
)

diffusion_models = [
    {
        "name": "Stable Diffusion XL Text2Img",
        "handler": "text2img",
        "description": "Generate images from text prompts.",
        "url_docs": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        "source": "stabilityai/stable-diffusion-xl-base-1.0",
        "pipeline": "StableDiffusionXLPipeline",
        "category": text2img,
    },
    {
        "name": "Runway ML Stable Diffusion v1.5",
        "handler": "text2img",
        "description": "Generate images from text prompts.",
        "url_docs": "https://huggingface.co/runwayml/stable-diffusion-v1-5",
        "source": "runwayml/stable-diffusion-v1-5",
        "pipeline": "StableDiffusionPipeline",
        "category": text2img,
    },
    {
        "name": "Stable Diffusion v2",
        "handler": "text2img",
        "description": "Generate images from text prompts.",
        "url_docs": "https://huggingface.co/stabilityai/stable-diffusion-2-1",
        "source": "stabilityai/stable-diffusion-2-1",
        "pipeline": "StableDiffusionPipeline",
        "category": text2img,
    },
    {
        "name": "Openjourney",
        "handler": "text2img",
        "description": "Generate images from text prompts.",
        "url_docs": "https://huggingface.co/prompthero/openjourney",
        "source": "prompthero/openjourney-v4",
        "pipeline": "StableDiffusionPipeline",
        "category": text2img,
    },
    {
        "name": "Stable Diffusion XL Img2Img",
        "handler": "img2img",
        "description": "Generate images from images.",
        "url_docs": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        "source": "stabilityai/stable-diffusion-xl-refiner-1.0",
        "pipeline": "StableDiffusionXLImg2ImgPipeline",
        "category": img2img,
    },
    {
        "name": "InstructPix2Pix",
        "handler": "img2img",
        "description": "Generate images from images.",
        "url_docs": "https://huggingface.co/timbrooks/instruct-pix2pix",
        "source": "timbrooks/instruct-pix2pix",
        "pipeline": "StableDiffusionXLImg2ImgPipeline",
        "category": img2img,
    },
    {
        "name": "Stable Diffusion v2",
        "handler": "img2img",
        "description": "Generate images from images.",
        "url_docs": "https://huggingface.co/stabilityai/stable-diffusion-2",
        "source": "stabilityai/stable-diffusion-2",
        "pipeline": "StableDiffusionImg2ImgPipeline",
        "category": img2img,
    },
    {
        "name": "Stable Diffusion XL Inpainting",
        "handler": "inpainting",
        "description": "Inpainting  lets you edit specific parts of an image by providing a mask and a text prompt.",
        "url_docs": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        "source": "stabilityai/stable-diffusion-xl-base-1.0",
        "pipeline": "StableDiffusionXLInpaintPipeline",
        "category": inpainting,
    },
    {
        "name": "Runway ML Stable Diffusion Inpainting",
        "handler": "inpainting",
        "description": "Inpainting  lets you edit specific parts of an image by providing a mask and a text prompt.",
        "url_docs": "https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/inpaint",
        "source": "runwayml/stable-diffusion-inpainting",
        "pipeline": "StableDiffusionInpaintPipeline",
        "category": inpainting,
    },
    {
        "name": "Stable Diffusion v2 Inpainting",
        "handler": "inpainting",
        "description": "Inpainting  lets you edit specific parts of an image by providing a mask and a text prompt.",
        "url_docs": "https://huggingface.co/stabilityai/stable-diffusion-2-inpainting",
        "source": "stabilityai/stable-diffusion-2-inpainting",
        "pipeline": "StableDiffusionInpaintPipeline",
        "category": inpainting,
    },
]
