from app.config.database.init_data.categories import (
    question_answering,
    text_to_text,
    text_classification,
    text_conversational,
    text_generation,
    text_summarization,
)

llm_models = [
    {
        "name": "Falcon Question and Answering V2",
        "handler": "question-answering-falcon",
        "description": "Answer questions given a context and a prompt.",
        "url_docs": "https://huggingface.co/Falconsai/question_answering_v2",
        "category": question_answering,
    },
    {
        "name": "DistilBERT base uncased distilled SQuAD",
        "handler": "question-answering-distilbert",
        "description": "Answer questions given a context and a prompt.",
        "url_docs": "https://huggingface.co/distilbert-base-uncased-distilled-squad",
        "category": question_answering,
    },
    {
        "name": "Google Flan T5 large",
        "handler": "text2text-google-flan",
        "description": "Translate, answer questions, do logical reasoning, and more.",
        "url_docs": "https://huggingface.co/google/flan-t5-large",
        "category": text_to_text,
    },
    {
        "name": "Flan Alpaca large",
        "handler": "text2text-alcapa",
        "description": "Translate, answer questions, do logical reasoning, and more.",
        "url_docs": "https://huggingface.co/declare-lab/flan-alpaca-large",
        "category": text_to_text,
    },
    {
        "name": "BART Large MNLI Probability",
        "handler": "text-classification-bart-nli",
        "description": "Get a true probability for a given sentence (classification) and a label.",
        "url_docs": "https://huggingface.co/facebook/bart-large-mnli",
        "category": text_classification,
    },
    {
        "name": "BART Large MNLI",
        "handler": "text-classification-bart",
        "description": "Classify text given a prompt and some labels",
        "url_docs": "https://huggingface.co/facebook/bart-large-mnli",
        "category": text_classification,
    },
    {
        "name": "Toxic BERT",
        "handler": "text-classification-toxic-bert",
        "description": "Toxic Comment Classification",
        "url_docs": "https://huggingface.co/unitary/toxic-bert",
        "category": text_classification,
    },
    {
        "name": "Roberta",
        "handler": "text-classification-roberta",
        "description": "Classify emotion given a prompt",
        "url_docs": "https://huggingface.co/SamLowe/roberta-base-go_emotions",
        "category": text_classification,
    },
    {
        "name": "ChatGLM-6B",
        "handler": "text-conversational-chat-glm",
        "description": "Chat with a conversational model.",
        "url_docs": "https://huggingface.co/THUDM/chatglm-6b",
        "category": text_conversational,
    },
    {
        "name": "Facebook Blenderbot 400M Distilled",
        "handler": "text-conversational-blenderbot",
        "description": "Chat with a conversational model.",
        "url_docs": "https://huggingface.co/facebook/blenderbot-400M-distill",
        "category": text_conversational,
    },
    {
        "name": "GPT2",
        "handler": "text-generation-gpt2",
        "description": "Generate text given a prompt.",
        "url_docs": "https://huggingface.co/gpt2",
        "category": text_generation,
    },
    {
        "name": "Microsoft Phi 1.5",
        "handler": "text-generation-phi15",
        "description": "Generate text given a prompt",
        "url_docs": "https://huggingface.co/microsoft/phi-1_5",
        "category": text_generation,
    },
    {
        "name": "OpenAI GPT",
        "handler": "text-generation-gpt",
        "description": "Generate text given a prompt",
        "url_docs": "https://huggingface.co/openai-gpt",
        "category": text_generation,
    },
    {
        "name": "Stable Beluga 7B",
        "handler": "text-generation-stable-beluga",
        "description": "Generate text given a prompt",
        "url_docs": "https://huggingface.co/stabilityai/StableBeluga-7B",
        "category": text_generation,
    },
    {
        "name": "BART Large CNN",
        "handler": "text-summarization-bart",
        "description": "BART (large-sized model), fine-tuned on CNN Daily Mail",
        "url_docs": "https://huggingface.co/facebook/bart-large-cnn",
        "category": text_summarization,
    },
    {
        "name": "DistilBART",
        "handler": "text-summarization-distilbart",
        "description": "Summarizes text using DistilBART",
        "url_docs": "https://huggingface.co/sshleifer/distilbart-cnn-12-6",
        "category": text_summarization,
    },
]
